"""Curve/affine-patch contacts from independent Fraction power-to-Bernstein data."""
from pathlib import Path
from fractions import Fraction as F
from math import comb,lcm
import random,json,struct
rng=random.Random(580058)
def mul(a,b):
    out=[F(0)]*(len(a)+len(b)-1)
    for i,x in enumerate(a):
        for j,y in enumerate(b):out[i+j]+=x*y
    return out
def f32(x):
    y=struct.unpack('f',struct.pack('f',float(x)))[0]
    assert F(y)==x,(x,y)
    return y
rows=[]
axes=[((1,0,0),(0,1,0),(0,0,1)),((1,2,0),(0,1,2),(4,-2,1)),((0,-2,0),(0,0,1),(-2,0,0))]
for index in range(64):
    degree=rng.randint(1,6)
    selected=rng.sample([F(-1,2),F(0),F(1,4),F(1,2),F(3,4),F(1),F(3,2)],rng.randint(1,min(3,degree)))
    multiplicities=[1]*len(selected)
    for _ in range(degree-len(selected)):multiplicities[rng.randrange(len(selected))]+=1
    p=[F(1)]
    for x,m in zip(selected,multiplicities):
        for _ in range(m):p=mul(p,[-x,F(1)])
    # Clear Bernstein conversion denominators before native float32 storage.
    scale=lcm(*(comb(degree,j)for j in range(degree+1)))
    bern=[scale*sum((p[j]*F(comb(k,j),comb(degree,j))for j in range(k+1)),F(0))for k in range(degree+1)]
    pool=[F(0),F(1,4),F(1,2),F(1)] if index%4 else [F(-1,4),F(5,4)]
    u,v=(rng.choice(pool)for _ in range(2))
    a,b,n=axes[index%len(axes)]
    o=(F(3),F(-2),F(1))
    weights=[F(2)**rng.randint(-2,2)for _ in range(degree+1)]
    points=[[f32(o[j]+u*a[j]+v*b[j]+n[j]*z/w)for j in range(3)]for z,w in zip(bern,weights)]
    expected=[dict(t=float(x),order=m,position=[f32(o[j]+u*a[j]+v*b[j])for j in range(3)])for x,m in sorted(zip(selected,multiplicities))if 0<=x<=1 and 0<=u<=1 and 0<=v<=1]
    rows.append(dict(points=points,degree=degree,weights=[float(w)for w in weights],plane=[list(map(float,o)),list(a),list(b)],u=float(u),v=float(v),roots=expected,knots=[-3]*(degree+1)+[5]*(degree+1)))
path=Path(__file__).resolve().parents[1]/'tests/CurvePlaneFixtures.luau'
path.write_text('-- Generated by tools/generate_curve_plane_fixtures.py using Fraction.\nreturn [==['+json.dumps(rows,separators=(',',':'))+']==]\n')
print(len(rows),'curve/plane references;',sum(len(x['roots'])for x in rows),'closed-domain contacts')
# Independent pointwise de Boor references for the raw-span power extractor.
def limbs(n):
    out=[]
    while n:out.append(n%(1<<24));n//=1<<24
    return out
def rational(x):return dict(sign=(x>0)-(x<0),n=limbs(abs(x.numerator)),d=limbs(x.denominator))
def deboor(controls,p,knots,t):
    n=len(controls)
    span=next((k for k in range(p,n)if knots[k]<=t<knots[k+1]),n-1)
    d=[list(controls[i])for i in range(span-p,span+1)]
    for level in range(1,p+1):
        for j in range(p,level-1,-1):
            k=span-p+j
            alpha=(t-knots[k])/(knots[k+p-level+1]-knots[k])
            d[j]=[(1-alpha)*a+alpha*b for a,b in zip(d[j-1],d[j])]
    return d[p]
powers=[]
for index in range(16):
    degree=1+index%5
    n=degree+4
    points=[[F(rng.randint(-8,8),4)for _ in range(3)]for _ in range(n)]
    weights=[F(2)**rng.randint(-3,3)for _ in range(n)]
    controls=[[*(x*w for x in point),w]for point,w in zip(points,weights)]
    clamped=index%2==0
    if clamped:
        interior=sorted(rng.sample([1,3,5,8,12],3))
        knots=[F(0)]*(degree+1)+list(map(F,interior))+[F(16)]*(degree+1)
    else:
        knots=[F(-16)]
        for _ in range(n+degree):knots.append(knots[-1]+rng.choice([1,2,4]))
    spans=[]
    for k in range(degree,n):
        lo,hi=knots[k:k+2]
        if lo==hi:continue
        samples=[dict(x=float(x),h=[rational(y)for y in deboor(controls,degree,knots,lo+x*(hi-lo))])for x in [F(0),F(1,4),F(1,2),F(3,4),F(1)]]
        spans.append(dict(index=k+1,offset=rational((lo-knots[degree])/(knots[n]-knots[degree])),scale=rational((hi-lo)/(knots[n]-knots[degree])),samples=samples))
    powers.append(dict(points=[[float(x)for x in point]for point in points],weights=list(map(float,weights)),degree=degree,knots=list(map(float,knots)),clamped=clamped,spans=spans))
path=Path(__file__).resolve().parents[1]/'tests/CurvePowerFixtures.luau'
path.write_text('-- Generated independently by Fraction de Boor in tools/generate_curve_plane_fixtures.py.\nreturn [==['+json.dumps(powers,separators=(',',':'))+']==]\n')
print(len(powers),'raw-knot curves;',sum(len(s['samples'])for c in powers for s in c['spans']),'homogeneous de Boor references;',path.stat().st_size,'bytes')
