from fractions import Fraction as F
from pathlib import Path
import json,random
rng=random.Random(612603)
def trim(p):
 while p and p[-1]==0:p.pop()
 return p
def add(a,b):return trim([(a[i] if i<len(a)else 0)+(b[i]if i<len(b)else 0)for i in range(max(len(a),len(b)))])
def mul(a,b):
 out=[0]*(len(a)+len(b)-1)
 for i,x in enumerate(a):
  for j,y in enumerate(b):out[i+j]+=x*y
 return trim(out)
def evalp(p,x):
 out=F(0)
 for a in p[::-1]:out=out*x+a
 return out
def determinant(a):
 a=[[F(x)for x in row]for row in a];out=F(1)
 for i in range(len(a)):
  pivot=next((j for j in range(i,len(a))if a[j][i]),None)
  if pivot is None:return F(0)
  if pivot!=i:a[pivot],a[i]=a[i],a[pivot];out=-out
  p=a[i][i];out*=p
  for j in range(i+1,len(a)):
   factor=a[j][i]/p
   for k in range(i+1,len(a)):a[j][k]-=factor*a[i][k]
 return out
def resultant_at(a,b,x):
 av=[evalp(p,x)for p in a][::-1];bv=[evalp(p,x)for p in b][::-1]
 m,n=len(a)-1,len(b)-1
 matrix=[]
 for i in range(n):matrix.append([0]*i+av+[0]*(n-i-1))
 for i in range(m):matrix.append([0]*i+bv+[0]*(m-i-1))
 return determinant(matrix)
def interpolate(values):
 out=[];basis=[F(1)]
 for x,y in values:
  factor=(y-evalp(out,x))/evalp(basis,x)
  out=add(out,[factor*c for c in basis])
  basis=mul(basis,[-x,F(1)])
 return out
def times_linear(a):
 out=[[]for _ in range(len(a)+1)]
 for i,p in enumerate(a):
  out[i]=add(out[i],mul(p,[0,1]))
  out[i+1]=add(out[i+1],p)
 return out
rows=[]
for i in range(32):
 m,n=1+i%3,1+(i//3)%3
 a=[trim([rng.randint(-3,3)for _ in range(3)])for _ in range(m+1)]
 b=[trim([rng.randint(-3,3)for _ in range(3)])for _ in range(n+1)]
 a[-1]=a[-1]or[1];b[-1]=b[-1]or[-1]
 if i%8==0:a,b=times_linear(a),times_linear(b)
 degree=(len(a)-1)*max(map(lambda p:len(p)-1,b))+(len(b)-1)*max(map(lambda p:len(p)-1,a))
 samples=[(F(k,3),resultant_at(a,b,F(k,3)))for k in range(degree+1)]
 expected=interpolate(samples)
 assert all(x.denominator==1 for x in expected)
 rows.append({'a':a,'b':b,'expected':[int(x)for x in expected]})
path = Path(__file__).resolve().parents[1] / 'tests' / 'TensorResultantFixtures.luau'
path.write_text('-- Generated by tools/generate_tensor_resultant_fixtures.py using independent Fraction references.\nreturn [==[' + json.dumps(rows, separators=(',', ':')) + ']==]\n')
print(len(rows),'independent Sylvester/Fraction interpolation references')
