"""Independent arithmetic in Q(sqrt(1/2)); no root-isolation implementation."""
from fractions import Fraction as F
from random import Random
from pathlib import Path
import json
rng=Random(580060)
def add(x,y):return x[0]+y[0],x[1]+y[1]
def sub(x,y):return x[0]-y[0],x[1]-y[1]
def mul(x,y):return x[0]*y[0]+x[1]*y[1]/2,x[0]*y[1]+x[1]*y[0]
def div(x,y):
    norm=y[0]*y[0]-y[1]*y[1]/2
    assert norm
    a,b=mul(x,(y[0],-y[1]));return a/norm,b/norm
def val(p):
    out=(F(0),F(0))
    for x in reversed(p):out=add(mul(out,(F(0),F(1))),(x,F(0)))
    return out
def sign(x):
    a,b=x
    if not a:return (b>0)-(b<0)
    if not b or (a>0)==(b>0):return (a>0)-(a<0)
    cmp=(a*a>b*b/2)-(a*a<b*b/2)
    return cmp*((a>0)-(a<0))
def limbs(n):
    out=[]
    while n:out.append(n%(1<<24));n//=1<<24
    return out
def rational(x):return dict(sign=(x>0)-(x<0),n=limbs(abs(x.numerator)),d=limbs(x.denominator))
def poly():return [F(rng.randint(-8,8),8)for _ in range(rng.randint(1,5))]
rows=[]
while len(rows)<384:
    an,ad,bn,bd=poly(),poly(),poly(),poly()
    if val(ad)==(0,0)or val(bd)==(0,0):continue
    if len(rows)<64:
        # Add an exact multiple of 2*s^2-1 to the numerator.
        bn=an+[F(0)]*max(0,3-len(an));k=F(rng.randint(1,8),4);bn[0]-=k;bn[2]+=2*k;bd=ad
    elif len(rows)<128:
        # Exact differences far below native parameter resolution.
        bd=ad;bn=an+[F(0)]*max(0,len(ad)-len(an));eps=F(rng.choice([-1,1]),2**rng.randint(60,128))
        for i,v in enumerate(ad):bn[i]+=eps*v
    expected=sign(sub(div(val(an),val(ad)),div(val(bn),val(bd))))
    rows.append(dict(a=dict(n=list(map(rational,an)),d=list(map(rational,ad))),b=dict(n=list(map(rational,bn)),d=list(map(rational,bd))),comparison=expected))
target=Path(__file__).resolve().parents[1]/'tests/AlgebraicValueFixtures.luau'
target.write_text('-- Generated by tools/generate_algebraic_value_fixtures.py.\nreturn [==['+json.dumps(rows,separators=(',',':'))+']==]\n')
print(len(rows),'independent quadratic-field rational comparisons')
