"""Independent exact polygon-clipping oracle for native-float32 UV triangle pairs."""
from fractions import Fraction as F
from pathlib import Path
import random
import struct


def f32(x):
    return struct.unpack('<f', struct.pack('<f', x))[0]


def cross(a, b, c):
    return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])


def overlap(a, b):
    a = [tuple(F(x) for x in p) for p in a]
    b = [tuple(F(x) for x in p) for p in b]
    if not cross(*a) or not cross(*b):
        return False
    if cross(*b) < 0:
        b.reverse()
    polygon = a
    for i, p in enumerate(b):
        q = b[(i+1) % 3]
        clipped = []
        if not polygon:
            break
        for j, x in enumerate(polygon):
            y = polygon[(j+1) % len(polygon)]
            dx, dy = cross(p, q, x), cross(p, q, y)
            if dx >= 0:
                clipped.append(x)
            if (dx < 0 < dy) or (dy < 0 < dx):
                t = dx/(dx-dy)
                clipped.append(tuple(x[k]+t*(y[k]-x[k]) for k in range(2)))
        polygon = clipped
    return bool(sum(p[0]*polygon[(i+1) % len(polygon)][1]-p[1]*polygon[(i+1) % len(polygon)][0]
                    for i, p in enumerate(polygon)))


rng = random.Random(270926)
base = [
    ([(0,0),(2,0),(0,2)], [(0,0),(2,0),(0,2)]),
    ([(0,0),(2,0),(0,2)], [(2,0),(2,2),(0,2)]),
    ([(0,0),(2,0),(0,2)], [(2,0),(3,0),(3,1)]),
    ([(0,0),(4,0),(0,4)], [(1,1),(2,1),(1,2)]),
    ([(0,0),(4,0),(2,4)], [(0,3),(4,3),(2,-1)]),
    ([(0,0),(4,0),(2,0)], [(0,0),(4,0),(2,4)]),
    ([(0,0),(8,1),(7,1)], [(0,0),(8,1),(8,2)]),
    ([(0,0),(8,1),(7,1)], [(7,1),(8,1),(8,2)]),
]
while len(base) < 64:
    base.append(tuple([tuple(rng.randint(-8,8) for _ in range(2)) for _ in range(3)] for _ in range(2)))
cases = []
for exponent in (-90,-30,0,30,90):
    for index, pair in enumerate(base):
        shift = 2**20 if index % 3 == 0 else 0
        scale = 2.0**exponent
        a,b = [[(f32((x+shift)*scale),f32((y-shift)*scale)) for x,y in tri] for tri in pair]
        if index % 2:
            a.reverse()
        if index % 4:
            b = b[1:]+b[:1]
        cases.append((a,b,overlap(a,b)))


def triangle(t):
    return '{'+','.join('{'+','.join(format(x,'.17g') for x in p)+'}' for p in t)+'}'


lines = ['-- Generated by tools/generate_uv_overlap_fixtures.py using exact Fraction polygon clipping.', 'return {']
for a,b,result in cases:
    lines.append('\t{a='+triangle(a)+',b='+triangle(b)+',overlap='+str(result).lower()+'},')
lines.append('}')
target = Path(__file__).resolve().parents[1]/'tests'/'UVOverlapFixtures.luau'
target.write_text('\n'.join(lines)+'\n')
print(f'{len(cases)} exact UV overlap fixtures; {sum(c[2] for c in cases)} positive-area pairs')
