"""Independent Fraction Bernstein evaluation and direct 1D half-space clipping."""
from fractions import Fraction as F
from math import comb
from random import Random
from pathlib import Path
import json
rng=Random(590001)
def limbs(n):
 out=[]
 while n:out.append(n%(1<<24));n//=1<<24
 return out
def rational(x):return dict(sign=(x>0)-(x<0),n=limbs(abs(x.numerator)),d=limbs(x.denominator))
def sub(a,b):return [x-y for x,y in zip(a,b)]
def cross(a,b):return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]
def dot(a,b):return sum((x*y for x,y in zip(a,b)),F(0))
def project(h,o,u,v):
 for x,y in [(0,1),(0,2),(1,2)]:
  det=u[x]*v[y]-u[y]*v[x]
  if det:
   q=[h[i]-o[i]*h[3]for i in range(3)]
   return [(q[x]*v[y]-q[y]*v[x])/det,(u[x]*q[y]-u[y]*q[x])/det]
 raise AssertionError('rank')
def clip(equations):
 low,high=F(0),F(1)
 for a,b in equations:
  if not b:
   if a<0:return None
  elif b>0:low=max(low,-a/b)
  else:high=min(high,-a/b)
 if low>high:return None
 return dict(low=rational(low),high=rational(high),dimension=int(low<high))
rows=[]
for index in range(64):
 degree=1+index%2
 o=list(map(F,[0,0,0]if index%3==0 else [2,-1,3]))
 u,v=([F(1),F(0),F(0)],[F(0),F(1),F(0)])if index%3==0 else ([F(1),F(2),F(0)],[F(0),F(1),F(2)])
 normal=cross(u,v)
 points=[];weights=[]
 for i in range(degree+1):
  prow=[];wrow=[]
  for j in range(2):
   x,y=F(rng.randint(-2,6),4),F(rng.randint(-2,6),4)
   z=F(0)if index%4==0 else F(rng.randint(-3,3),4)
   p=[o[k]+x*u[k]+y*v[k]+z*normal[k]for k in range(3)]
   prow.append(p);wrow.append(F(2)**rng.randint(-2,2))
  points.append(prow);weights.append(wrow)
 probes=[]
 for step in range(9):
  s=F(step,8)
  endpoints=[]
  for side in range(2):
   h=[F(0)]*4
   for i in range(degree+1):
    basis=comb(degree,i)*s**i*(1-s)**(degree-i)
    w=weights[i][side]
    for axis in range(3):h[axis]+=basis*w*points[i][side][axis]
    h[3]+=basis*w
   endpoints.append(h)
  a=endpoints[0];b=sub(endpoints[1],a)
  f=dot(normal,sub(a[:3],[x*a[3]for x in o]));g=dot(normal,sub(b[:3],[x*b[3]for x in o]))
  ap,bp=project(a,o,u,v),project(b,o,u,v)
  equations=[(f,g),(-f,-g)]
  for axis in range(2):equations.extend([(ap[axis],bp[axis]),(a[3]-ap[axis],b[3]-bp[axis])])
  probes.append(dict(s=float(s),fiber=clip(equations)))
 rows.append(dict(degree=degree,points=[[[float(x)for x in p]for p in row]for row in points],weights=[[float(w)for w in row]for row in weights],plane=[list(map(float,x))for x in [o,u,v]],probes=probes))
target=Path(__file__).resolve().parents[1]/'tests/RuledPlaneFixtures.luau'
target.write_text('-- Generated by tools/generate_ruled_plane_fixtures.py with Fraction.\nreturn [==['+json.dumps(rows,separators=(',',':'))+']==]\n')
print(len(rows),'independent ruled surfaces;',sum(len(r['probes'])for r in rows),'exact clipped fibers;',sum(p['fiber']is not None for r in rows for p in r['probes']),'feasible')
