"""Independent factored rational/irreducible-quadratic references; no Sturm solver."""
from pathlib import Path
from fractions import Fraction as F
from decimal import Decimal, localcontext, ROUND_FLOOR
import random, math, json
root=Path(__file__).resolve().parents[1]
rng=random.Random(580021)
def mul(a,b):
    out=[F(0)]*(len(a)+len(b)-1)
    for i,x in enumerate(a):
        for j,y in enumerate(b):out[i+j]+=x*y
    return out
def value(p,t):
    out=F(0)
    for x in reversed(p):out=out*t+x
    return out
def stored(p):
    out=[float(x) for x in p]
    assert all(F(y)==x for x,y in zip(p,out))
    return out
def limbs(n):
    out=[]
    while n:out.append(n%(1<<24));n//=1<<24
    return out
def rational(x):return dict(sign=(x>0)-(x<0),n=limbs(abs(x.numerator)),d=limbs(x.denominator))
rows=[]
for _ in range(64):
    factors=[(F(x,4),rng.randint(1,3)) for x in rng.sample([-8,-4,-3,-2,-1,0,1,2,3,4,8],rng.randint(1,4))]
    p=[F(rng.choice([-8,-3,1,5]))]
    for x,m in factors:
        for _ in range(m):p=mul(p,[-x,F(1)])
    if rng.randrange(2):p=mul(p,[F(1),F(0),F(1)])
    expected=[dict(x=float(x),multiplicity=m)for x,m in sorted(factors)if -1<=x<=1]
    rows.append(dict(coefficients=stored(p),roots=expected,factors=[dict(root=float(x),multiplicity=m)for x,m in factors]))
quadratics=[]
choices=[(b,c) for b in range(-4,5)for c in range(-4,5)if b*b-4*c>0 and math.isqrt(b*b-4*c)**2!=b*b-4*c]
for _ in range(64):
    factors=[(b,c,rng.randint(1,2))for b,c in rng.sample(choices,rng.randint(1,3))]
    p=[F(rng.choice([-3,1,5]))]
    for b,c,m in factors:
        for _ in range(m):p=mul(p,[F(c),F(b),F(1)])
    expected=[]
    with localcontext()as context:
        context.prec=100
        for b,c,m in factors:
            d=Decimal(b*b-4*c).sqrt()
            for x in [(-Decimal(b)-d)/2,(-Decimal(b)+d)/2]:
                if not -2<x<2:continue
                n=int((x*Decimal(2**64)).to_integral_value(rounding=ROUND_FLOOR))
                lo,hi=F(n,2**64),F(n+1,2**64)
                assert value([F(c),F(b),F(1)],lo)*value([F(c),F(b),F(1)],hi)<0
                # A distinct irreducible quadratic cannot share this algebraic root.
                expected.append((x,dict(low=rational(lo),high=rational(hi),multiplicity=m)))
    quadratics.append(dict(coefficients=stored(p),roots=[row for _,row in sorted(expected)],factors=[dict(b=b,c=c,multiplicity=m)for b,c,m in factors]))
fixture=dict(rational=rows,quadratic=quadratics)
(root/'tests/PolynomialRootFixtures.luau').write_text('-- Generated by tools/generate_polynomial_root_fixtures.py; factorizations and exact brackets.\nreturn [==['+json.dumps(fixture,separators=(',',':'))+']==]\n')
print('128 cases;',sum(len(x['roots'])for group in fixture.values()for x in group),'reference roots')
