"""Independent exact Fraction and IEEE754 nextafter fixtures; no Luau implementation imports."""
from pathlib import Path
from fractions import Fraction
import math
import random
import struct

root = Path(__file__).resolve().parents[1] / "tests"
rng = random.Random(20260927)

def bits(value):
    return struct.pack(">d", value).hex()

def random_finite():
    while True:
        value = struct.unpack(">d", rng.getrandbits(64).to_bytes(8, "big"))[0]
        if math.isfinite(value):
            return value

def directed(value):
    try:
        rounded = float(value)
    except OverflowError:
        rounded = math.copysign(math.inf, 1 if value > 0 else -1)
    if rounded == math.inf:
        return math.nextafter(rounded, -math.inf), rounded
    if rounded == -math.inf:
        return rounded, math.nextafter(rounded, math.inf)
    exact = Fraction(rounded)
    return (math.nextafter(rounded, -math.inf) if exact > value else rounded,
            math.nextafter(rounded, math.inf) if exact < value else rounded)

def pair(a, b):
    return '{"' + bits(a) + '","' + bits(b) + '"}'

values = [0., -0., math.inf, -math.inf, 5e-324, -5e-324, 1., -1.,
          2.2250738585072014e-308, 1.7976931348623157e308]
values += [random_finite() for _ in range(500)]
steps = ['{"' + bits(v) + '","' + bits(math.nextafter(v, math.inf)) + '","'
         + bits(math.nextafter(v, -math.inf)) + '"}' for v in values]
cases = []
inputs = [(sorted([random_finite(), random_finite()]), sorted([random_finite(), random_finite()])) for _ in range(500)]
normal = 2.2250738585072014e-308
for x in (5e-324, -5e-324, normal, -normal, math.nextafter(normal, 0), -math.nextafter(normal, 0)):
    for y in (.5, 2., x, -x):
        inputs.append(([x, x], [y, y]))
for x, y in ((normal, math.nextafter(normal, math.inf)), (1e-300, 1e-20),
             (1e-300, 1e300), (1., 5e-324), (1.7976931348623157e308, 2.),
             (1e308, -1e308), (0., 5e-324), (5e-324, 0.)):
    inputs.append(([x, x], [y, y]))
counts = {operation: 0 for operation in ("add", "sub", "mul", "div")}
for x in (0., -0., 5e-324, -5e-324, normal, -normal, 1., -1.,
          1e-100, -1e-100, 1.7976931348623157e308, -1.7976931348623157e308):
    for y in (0., 1., -1., x):
        inputs.append(([x, x], [y, y]))
for a, b in inputs:
    af, bf = list(map(Fraction, a)), list(map(Fraction, b))
    for operation in ("add", "sub", "mul", "div"):
        if operation == "add":
            ends = [af[0] + bf[0], af[1] + bf[1]]
        elif operation == "sub":
            ends = [af[0] - bf[1], af[1] - bf[0]]
        elif operation == "mul":
            ends = [x * y for x in af for y in bf]
        elif bf[0] <= 0 <= bf[1]:
            continue
        else:
            ends = [x / y for x in af for y in bf]
        lo, hi = directed(min(ends))[0], directed(max(ends))[1]
        cases.append('{"' + operation + '",' + pair(*a) + ',' + pair(*b) + ',' + pair(lo, hi) + '}')
        counts[operation] += 1
for index, start in enumerate(range(0, len(cases), 700), 1):
    source = '-- Generated by tools/generate_interval_fixtures.py; values encoded as IEEE754 hex.\n'
    source += 'return {steps={' + ',\n'.join(steps if start == 0 else [])
    source += '}, counts={' + ','.join(f'{name}={count}' for name,count in counts.items()) + '}, arithmetic={' + ',\n'.join(cases[start:start + 700]) + '}}\n'
    assert len(source) < 200000
    (root / f"IntervalFixtures{index}.luau").write_text(source)
print(f"Generated {len(steps)} nextafter pairs and {len(cases)} exact arithmetic intervals: {counts}")
