"""Independent exact-Fraction triangle-overlay oracle for quad coarsening."""
from fractions import Fraction as F
from pathlib import Path
import math
import random
import struct


def cross(a, b, c):
    return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])


def clip(polygon, triangle):
    for a, b in zip(triangle, triangle[1:]+triangle[:1]):
        result = []
        for p, q in zip(polygon, polygon[1:]+polygon[:1]):
            dp, dq = cross(a, b, p), cross(a, b, q)
            if dp >= 0:
                result.append(p)
            if (dp >= 0) != (dq >= 0):
                t = dp/(dp-dq)
                result.append(tuple(p[k]+t*(q[k]-p[k]) for k in range(2)))
        polygon = result
        if not polygon:
            break
    return polygon


def interpolate(triangle, positions, point):
    a, b, c = triangle
    denominator = cross(a, b, c)
    weights = [cross(b, c, point)/denominator,
               cross(c, a, point)/denominator,
               cross(a, b, point)/denominator]
    return tuple(sum(weights[i]*positions[triangle[i]][k] for i in range(3))
                 for k in range(3))


def triangulate(quad):
    # For these convex dominant-axis projections, the source mesh ear order
    # starts with (last, first, second), then the remaining three corners.
    return [(quad[3], quad[0], quad[1]), (quad[1], quad[2], quad[3])]


def exact_maximum(positions, rotations):
    target = triangulate(((F(0), F(0)), (F(2), F(0)), (F(2), F(2)), (F(0), F(2))))
    maximum = F(0)
    overlaps = []
    for i in range(2):
        for j in range(2):
            q = [(F(i), F(j)), (F(i+1), F(j)), (F(i+1), F(j+1)), (F(i), F(j+1))]
            rotation = rotations[i*2+j]
            q = q[rotation:]+q[:rotation]
            for source in triangulate(q):
                overlap_row = []
                for coarse in target:
                    polygon = clip(list(source), list(coarse))
                    area2 = sum(p[0]*q[1]-p[1]*q[0] for p, q in zip(polygon, polygon[1:]+polygon[:1]))
                    overlap_row.append(area2 > 0)
                    for uv in polygon:
                        a, b = interpolate(source, positions, uv), interpolate(coarse, positions, uv)
                        maximum = max(maximum, sum((a[k]-b[k])**2 for k in range(3)))
                overlaps.append(overlap_row)
    return maximum, overlaps


def sqrt_up(q):
    if q == 0:
        return 0.0
    x = math.sqrt(float(q))
    while F(x)**2 < q:
        x = math.nextafter(x, math.inf)
    while F(math.nextafter(x, -math.inf))**2 >= q:
        x = math.nextafter(x, -math.inf)
    return x


def f32(x):
    return struct.unpack('>f', struct.pack('>f', x))[0]


def lua(value):
    if isinstance(value, list):
        return '{'+', '.join(lua(v) for v in value)+'}'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    return repr(value)


rng = random.Random(50319)
fixtures = []
for exponent in (-60, -15, 0, 20, 60):
    scale = 2.0**exponent
    for pattern in range(16):
        rotations = [(pattern >> i) & 1 for i in range(4)]
        offset = (0, 2**10, 2**18, -(2**18))[pattern % 4]*scale
        permutation = pattern % 3
        positions = {}
        native = []
        for i in range(3):
            for j in range(3):
                z = rng.randrange(-64, 65)/512
                p = [f32(offset+i*scale), f32(-offset+j*scale), f32(offset+z*scale)]
                p = p[permutation:]+p[:permutation]
                positions[(F(i), F(j))] = tuple(F(v) for v in p)
                native.append(p)
        maximum, overlaps = exact_maximum(positions, rotations)
        fixtures.append((native, rotations, sqrt_up(maximum), overlaps))

lines = ['-- Generated by tools/generate_unsubdivide_fixtures.py using exact Fraction polygon overlays.', 'return {']
for positions, rotations, upper, overlaps in fixtures:
    lines.append('\t{ positions = '+lua(positions)+', rotations = '+lua(rotations)+', upper = '+repr(upper)+', overlaps = '+lua(overlaps)+' },')
lines.append('}')
output = Path(__file__).resolve().parents[1]/'tests'/'UnsubdivideFixtures.luau'
output.write_text('\n'.join(lines)+'\n')
print(f'Wrote {len(fixtures)} exact rational overlay fixtures')
