"""Independent Fraction clipping / segment intersection references."""
from fractions import Fraction as F
import json
import random
from pathlib import Path


def multiply(p, q):
    out = [[0] * (len(p[0]) + len(q[0]) - 1) for _ in range(len(p) + len(q) - 1)]
    for i, row in enumerate(p):
        for j, x in enumerate(row):
            for k, other in enumerate(q):
                for l, y in enumerate(other):
                    out[i + k][j + l] += x * y
    return out


def segment(line):
    a, b, c = map(F, line)
    points = set()
    for x in (F(0), F(1)):
        if b:
            y = -(c + a * x) / b
            if 0 <= y <= 1:
                points.add((x, y))
    for y in (F(0), F(1)):
        if a:
            x = -(c + b * y) / a
            if 0 <= x <= 1:
                points.add((x, y))
    return sorted(points)


def intersects(first, second):
    a, b, c = map(F, first)
    d, e, f = map(F, second)
    determinant = a * e - b * d
    if not determinant:
        return a * f == c * d and b * f == c * e
    x, y = (b * f - c * e) / determinant, (c * d - a * f) / determinant
    return 0 <= x <= 1 and 0 <= y <= 1


def reference(lines):
    segments = [line for line in lines if segment(line)]
    parent = list(range(len(segments)))

    def root(i):
        while i != parent[i]:
            i = parent[i]
        return i

    for i, first in enumerate(segments):
        for j, second in enumerate(segments[:i]):
            if intersects(first, second):
                parent[root(i)] = root(j)
    groups = {}
    for i, line in enumerate(segments):
        groups.setdefault(root(i), []).append(line)
    dimensions = sorted(max(len(segment(line)) > 1 for line in group) * 1 for group in groups.values())
    return dimensions


rng = random.Random(43187)
rows = []
cases = [
    [(1, 1, 0), (1, 1, -2)],
    [(1, 0, 0), (1, 0, -1), (0, 1, 0)],
    [(1, 1, -1), (1, -1, 0), (2, 2, -2)],
    [(4, 0, -1), (4, 0, -3), (0, 4, -2)],
    [(4, 0, -1), (4, 0, -3), (0, 1, -2)],
]
for _ in range(35):
    lines = []
    for _ in range(rng.randint(1, 3)):
        while True:
            line = tuple(rng.randint(-4, 4) for _ in range(3))
            if line[0] or line[1]:
                break
        lines.append(line)
    cases.append(lines)
for lines in cases:
    p = [[1]]
    for a, b, c in lines:
        p = multiply(p, [[c, a], [b, 0]])
    rows.append(dict(lines=lines, polynomial=p, dimensions=reference(lines)))
path = Path(__file__).resolve().parents[1] / 'tests' / 'TensorLineFixtures.luau'
path.write_text('-- Generated by tools/generate_planar_line_fixtures.py using independent Fraction references.\nreturn [==[' + json.dumps(rows, separators=(',', ':')) + ']==]\n')
print(f'{len(rows)} independent exact line-arrangement references')
