"""Independent pointwise Fraction de Boor references for tensor extraction."""
from fractions import Fraction as F
from pathlib import Path
import json
import random

rng = random.Random(610061)


def limbs(n):
    out = []
    while n:
        out.append(n % (1 << 24))
        n //= 1 << 24
    return out


def rational(x):
    return dict(sign=(x > 0) - (x < 0), n=limbs(abs(x.numerator)), d=limbs(x.denominator))


def deboor(controls, degree, knots, t):
    n = len(controls)
    span = next((i for i in range(degree, n) if knots[i] <= t < knots[i + 1]), n - 1)
    d = [list(controls[i]) for i in range(span - degree, span + 1)]
    for level in range(1, degree + 1):
        for j in range(degree, level - 1, -1):
            k = span - degree + j
            alpha = (t - knots[k]) / (knots[k + degree - level + 1] - knots[k])
            d[j] = [(1 - alpha) * a + alpha * b for a, b in zip(d[j - 1], d[j])]
    return d[degree]


rows = []
for index in range(16):
    du, dv = index % 3 + 1, (index // 3) % 3 + 1
    nu, nv = du + 2, dv + 2
    clamped_u, clamped_v = index % 2 == 0, index % 3 != 0
    point_scale = F(2) ** [-32, 0, 32, 0][index % 4]
    weight_scale = F(2) ** [-120, 0, 120, 0][index % 4]
    knot_scale = F(2) ** [-900, 0, 900, 0][index % 4]
    control = [[[F(rng.randint(-8, 8), 4) * point_scale for _ in range(3)] for _ in range(nv)] for _ in range(nu)]
    weights = [[F(2) ** rng.randint(-3, 3) * weight_scale for _ in range(nv)] for _ in range(nu)]
    homogeneous = [[[*(x * weights[i][j] for x in control[i][j]), weights[i][j]] for j in range(nv)] for i in range(nu)]

    def knots(degree, count, clamped):
        values = [-3] * (degree + 1) + [2] + [9] * (degree + 1) if clamped else list(range(-degree - 3, count - 2))
        assert len(values) == count + degree + 1
        return [F(x) * knot_scale for x in values]

    ku, kv = knots(du, nu, clamped_u), knots(dv, nv, clamped_v)
    spans = []
    for u_span in range(du, nu):
        for v_span in range(dv, nv):
            offset = [(ku[u_span] - ku[du]) / (ku[nu] - ku[du]), (kv[v_span] - kv[dv]) / (kv[nv] - kv[dv])]
            scale = [(ku[u_span + 1] - ku[u_span]) / (ku[nu] - ku[du]), (kv[v_span + 1] - kv[v_span]) / (kv[nv] - kv[dv])]
            samples = []
            for s in (F(0), F(1, 2), F(1)):
                u = ku[u_span] + s * (ku[u_span + 1] - ku[u_span])
                row = [deboor([homogeneous[i][j] for i in range(nu)], du, ku, u) for j in range(nv)]
                for t in (F(0), F(1, 2), F(1)):
                    v = kv[v_span] + t * (kv[v_span + 1] - kv[v_span])
                    value = deboor(row, dv, kv, v)
                    samples.append(dict(s=float(s), t=float(t), h=[rational(x) for x in value]))
            spans.append(dict(knots=[u_span + 1, v_span + 1], offset=list(map(rational, offset)), scale=list(map(rational, scale)), samples=samples))
    rows.append(dict(control=[[[float(x) for x in point] for point in row] for row in control], weights=[[float(w) for w in row] for row in weights], degreeU=du, degreeV=dv, knotsU=list(map(float, ku)), knotsV=list(map(float, kv)), clampedU=clamped_u, clampedV=clamped_v, spans=spans))

path = Path(__file__).resolve().parents[1] / 'tests' / 'TensorPowerFixtures.luau'
path.write_text('-- Generated by tools/generate_tensor_power_fixtures.py using independent Fraction de Boor.\nreturn [==[' + json.dumps(rows, separators=(',', ':')) + ']==]\n')
print(len(rows), 'tensor surfaces;', sum(len(s['samples']) for row in rows for s in row['spans']), 'independent homogeneous evaluations;', path.stat().st_size, 'bytes')
