"""Independent Fraction recurrences and big-integer normalization references."""
from fractions import Fraction as F
from pathlib import Path
import json, random

rng = random.Random(731904)

def product(a,b):
    return [[sum((x*y for x,y in zip(row,col)),F(0)) for col in zip(*b)] for row in a]

def inverse(a):
    n=len(a); rows=[row[:]+[F(i==j) for j in range(n)] for i,row in enumerate(a)]
    for j in range(n):
        pivot=next(i for i in range(j,n) if rows[i][j]); rows[j],rows[pivot]=rows[pivot],rows[j]
        t=rows[j][j]; rows[j]=[x/t for x in rows[j]]
        for i in range(n):
            if i!=j:
                t=rows[i][j]; rows[i]=[x-t*y for x,y in zip(rows[i],rows[j])]
    return [row[n:] for row in rows]

def recurrence(matrix,source):
    basis=[]; powers=[]
    for k in range(len(matrix)+1):
        flat=[x for row in source for x in row]; powers.append(flat); value=flat[:]; p=[F(0)]*k+[F(1)]
        for pivot,b,q in basis:
            t=value[pivot]; value=[x-t*y for x,y in zip(value,b)]
            for j,x in enumerate(q): p[j]-=t*x
        pivot=next((i for i,x in enumerate(value) if x),None)
        if pivot is None:
            assert all(sum(p[j]*powers[j][i] for j in range(len(p)))==0 for i in range(len(flat)))
            return p
        t=value[pivot]; basis.append((pivot,[x/t for x in value],[x/t for x in p]))
        source=product(matrix,source)
    raise AssertionError('Cayley-Hamilton bound')

def encode(x): return [str(x.numerator),str(x.denominator)]
def limbs(x):
    out=[]
    while x: out.append(x%(1<<24)); x>>=24
    return out

cases=[]
for n in range(1,9):
    for family in range(4):
        j=[[F(0) for _ in range(n)] for _ in range(n)]
        for i in range(n):
            j[i][i]=F(0) if family==3 else F(1,2) if family==1 else F(2*i+1,16)
            if family in (1,3) and i+1<n: j[i][i+1]=F(1)
        s=[[F(i==k) for k in range(n)] for i in range(n)]
        for i in range(1,n): s[i][i-1]=F((-1)**i)
        matrix=product(product(s,j),inverse(s))
        raw=[[F(rng.randrange(-5,6),16777213 if family==2 else 1) for _ in range(3)] for _ in range(n)]
        if family==2:
            for row in raw[n//2:]: row[:]=[F(0)]*3
        source=product(s,raw)
        cases.append({'matrix':[[encode(x) for x in row] for row in matrix], 'source':[[encode(x) for x in row] for row in source], 'polynomial':[encode(x) for x in recurrence(matrix,source)]})

arithmetic=[]
for i in range(128):
    common=[1<<rng.randrange(1,512),16777213,(1<<24)-1,(1<<73)+17][i%4]
    numerator=rng.getrandbits(1+(i*37)%700)+1
    denominator=rng.getrandbits(1+(i*29)%600)+1
    fraction=F(numerator,denominator)
    arithmetic.append({'sign':-1 if i%3==0 else 1,'n':limbs(numerator*common),'d':limbs(denominator*common),'expectedN':limbs(fraction.numerator),'expectedD':limbs(fraction.denominator)})

out={'recurrences':cases,'arithmetic':arithmetic,'fourNormal':[0.05862575729737828,0.3416083860158976,-0.9380121167580525]}
text=json.dumps(out,separators=(',',':'))
assert len(text)<190000
path=Path(__file__).resolve().parents[1]/'tests'/'AnnularNormalFixtures.luau'
path.write_text('-- Generated by tools/generate_annular_normal_fixtures.py.\nreturn [==['+text+']==]\n')
print(len(cases),'recurrences',len(arithmetic),'arithmetic cases',len(text),'bytes')
