"""Independent Fraction clipping oracle for native-coordinate triangle intersections."""
from fractions import Fraction as F
from pathlib import Path
import random
import struct

ROOT = Path(__file__).resolve().parents[1]
rng = random.Random(42167)

def f32(value):
    return struct.unpack('<f', struct.pack('<f', value))[0]

def sub(a, b): return tuple(x-y for x, y in zip(a, b))
def dot(a, b): return sum(x*y for x, y in zip(a, b))
def cross(a, b): return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])
def normal(tri): return cross(sub(tri[1], tri[0]), sub(tri[2], tri[0]))
def project(p, axis): return p[(axis+1)%3], p[(axis+2)%3]
def orient(a, b, c): return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
def sign(x): return int(x>0)-int(x<0)

def segment(a, b, tri):
    n = normal(tri)
    da, db = dot(n, sub(a, tri[0])), dot(n, sub(b, tri[0]))
    if da * db > 0: return []
    axis = max(range(3), key=lambda i: abs(n[i]))
    uv = [project(p, axis) for p in tri]
    winding = sign(orient(*uv))
    if da or db:
        t = da/(da-db)
        p = tuple(x+(y-x)*t for x, y in zip(a, b))
        q = project(p, axis)
        return [p] if all(orient(uv[i], uv[(i+1)%3], q)*winding >= 0 for i in range(3)) else []
    lo, hi = F(0), F(1)
    aa, bb = project(a, axis), project(b, axis)
    for i in range(3):
        x = orient(uv[i], uv[(i+1)%3], aa)*winding
        y = orient(uv[i], uv[(i+1)%3], bb)*winding
        if x < 0 and y < 0: return []
        if x < 0: lo = max(lo, x/(x-y))
        if y < 0: hi = min(hi, x/(x-y))
    if lo > hi: return []
    return list({tuple(x+(y-x)*t for x, y in zip(a,b)) for t in (lo,hi)})

def classify(a, b):
    points = set()
    for i in range(3):
        points.update(segment(a[i], a[(i+1)%3], b))
        points.update(segment(b[i], b[(i+1)%3], a))
    points = sorted(points)
    dimension = -1 if not points else 0 if len(points)==1 else 1
    if len(points)>2 and any(any(cross(sub(p,points[0]), sub(points[1],points[0]))) for p in points[2:]):
        dimension=2
    sa = [sign(dot(normal(b), sub(p,b[0]))) for p in a]
    sb = [sign(dot(normal(a), sub(p,a[0]))) for p in b]
    coplanar = not any(sa)
    kind = 'overlap' if dimension==2 else 'crossing' if dimension==1 and min(sa)<0<max(sa) and min(sb)<0<max(sb) else 'contact'
    return dimension, kind, coplanar

cases=[]
def put(a,b):
    a,b = [[tuple(F(f32(x)) for x in p) for p in tri] for tri in (a,b)]
    if any(normal(a)) and any(normal(b)):
        cases.append((a,b,*classify(a,b)))

for coplanar in (False,True):
    for _ in range(96):
        tris=[[[rng.randrange(-8,9) for _ in range(3)] for _ in range(3)] for _ in range(2)]
        if coplanar:
            for tri in tris:
                for p in tri: p[2]=3
        put(*tris)

base=[(-1,-1,0),(1,-1,0),(0,1,0)]
special=[[(0,0,-1),(0,0,1),(0,2,0)], base,
         [(1,-1,0),(3,-1,0),(2,1,0)], [(0,0,0),(1,0,0),(0,1,0)],
         [(-1,-1,2**-100),(1,-1,2**-100),(0,1,2**-100)],
         [(0,0,-2**-100),(0,0,2**-100),(0,1,2**100)],
         [(0,0,0),(0,2**-100,0),(1,2**100,0)]]
for b in special: put(base,b)
for exponent in (-120,-70,0,70,120):
    scale=2.0**exponent
    for b in special[:4]:
        put([[x*scale for x in p] for p in base], [[x*scale for x in p] for p in b])
for exponent in (-90,0,90):
    scale=2.0**exponent
    tiny=scale*2**-20
    a=[(0,0,0),(scale,scale,0),(-scale,-scale,tiny)]
    for b in [[(0,0,0),(tiny,0,scale),(0,tiny,-scale)],
              [(tiny,0,scale),(0,tiny,scale),(tiny,tiny,2*scale)]]:
        put(a,b)

def vector(p): return 'Vector3.new('+','.join(format(float(x),'.17g') for x in p)+')'
def triangle(t): return '{'+','.join(vector(p) for p in t)+'}'
lines=['-- Generated by tools/intersection_fixtures.py with an independent Fraction clipping oracle.','return {']
for a,b,dimension,classification,coplanar in cases:
    lines.append('{a='+triangle(a)+',b='+triangle(b)+',dimension='+str(dimension)+',classification="'+classification+'",coplanar='+str(coplanar).lower()+'},')
lines.append('}')
(ROOT/'tests/IntersectionFixtures.luau').write_text('\n'.join(lines)+'\n')
print(f'{len(cases)} independent exact triangle-intersection fixtures')
