"""Independent exact rational oracle for native float32 predicate fixtures."""
from fractions import Fraction
from pathlib import Path
import math
import random
import struct

ROOT = Path(__file__).resolve().parents[1]
rng = random.Random(32617)

def f32(x):
    return struct.unpack('<f', struct.pack('<f', x))[0]

def determinant(m):
    if len(m) == 1:
        return m[0][0]
    return sum((-1)**j * m[0][j] * determinant([row[:j]+row[j+1:] for row in m[1:]]) for j in range(len(m)))

def value(kind, points, exact=True):
    data = [[Fraction(v) if exact else v for v in p] for p in points]
    if kind == 'orient3D':
        origin, others = data[0], data[1:]
    else:
        origin, others = data[-1], data[:-1]
    matrix = [[a-b for a,b in zip(p,origin)] for p in others]
    if kind in ('inCircle','inSphere'):
        matrix = [row+[sum(v*v for v in row)] for row in matrix]
    d = determinant(matrix)
    return -d if kind == 'inSphere' else d

def sign(x):
    return int(x>0)-int(x<0)

cases=[]
for kind,dim,count in [('orient2D',2,3),('orient3D',3,4),('inCircle',2,4),('inSphere',3,5)]:
    for k in range(48):
        points = [[f32(math.ldexp(rng.choice([-1,1])*(1+rng.random()),rng.randint(-120,120))) for _ in range(dim)] for _ in range(count)]
        cases.append((kind,points))

for exponent in [-100,-30,0,30,100]:
    scale=2.0**exponent
    tiny=scale*2**-80 if exponent>=-30 else scale*2**-20
    a,b,c=[[-0.5*tiny,0.5*tiny],[scale,scale],[-scale,-scale]]
    cases.extend([
        ('orient2D',[a,b,c]),
        ('orient2D',[a,c,b]),
        ('orient3D',[[0,0,0],[scale,scale,0],[-scale,-scale,tiny],[tiny,0,scale]]),
        ('inCircle',[[scale,0],[0,scale],[-scale,0],[tiny,-scale]]),
        ('inCircle',[[scale,0],[0,scale],[-scale,0],[0,-scale]]),
        ('inSphere',[[scale,0,0],[0,scale,0],[-scale,0,0],[0,0,scale],[tiny,0,-scale]]),
        ('inSphere',[[scale,0,0],[0,scale,0],[-scale,0,0],[0,0,scale],[0,0,-scale]]),
    ])

lines=['-- Generated by tools/predicate_fixtures.py using Python Fraction arithmetic.','return {']
naive_failures=0
for kind, raw in cases:
    points=[[f32(v) for v in p] for p in raw]
    expected=sign(value(kind,points))
    naive_failures+=sign(value(kind,points,False))!=expected
    vectors=','.join(('Vector2' if len(p)==2 else 'Vector3')+'.new('+','.join(format(v,'.17g') for v in p)+')' for p in points)
    lines.append('{kind="'+kind+'", expected='+str(expected)+', points={'+vectors+'}},')
lines.append('}')
(ROOT/'tests/PredicateFixtures.luau').write_text('\n'.join(lines)+'\n')
print(f'{len(cases)} exact fixtures; {naive_failures} disagree with naive binary64 determinants')
